# NapCat 工具配置

TOOL_NAME="NapCat"
TOOL_REPO="https://github.com/NapNeko/NapCatQQ/releases/latest/download/NapCat.Shell.zip"
TOOL_INSTALL_DIR="/root/cs/Napcat"
TOOL_DEPS=(node linuxqq)
TOOL_START_CMD="xvfb-run -a /opt/QQ/qq --no-sandbox"

# NapCat 专用变量
CONFIG_DIR="/root/cs/Napcat/config"
NAPCATBOT_FILE="/root/cs/Napcat/Napcatbot"
QQ_PACKAGE_JSON="/opt/QQ/resources/app/package.json"
LOAD_NAPCAT_JS="/opt/QQ/resources/app/loadNapCat.js"
QQ_BIN="/opt/QQ/qq"
